"""Dependency-free static publishing pipeline. Python 3.12+."""
import html, json, pathlib, shutil
ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / 'dist'
data = json.loads((ROOT / 'content.json').read_text(encoding='utf-8'))
module = json.loads((ROOT / 'modules' / 'introduction.json').read_text(encoding='utf-8'))
data['chapters'] = module['chapters'] + data['chapters']
data['sources'] += module['sources']
data['reviewed'] = '2026-09-24'
sources = {s['id']: s for s in data['sources']}
e = html.escape

def refs(ids):
    return '<ul class="source-list">' + ''.join(f'<li><a href="{sources[i]["url"]}" target="_blank" rel="noopener noreferrer">{e(sources[i]["title"])} ↗</a><p>{e(sources[i].get("supports", sources[i].get("publisher", "Public source") + " · " + sources[i].get("type", "Reference")))}</p></li>' for i in ids) + '</ul>'

def shell(title, body, active='guide', slug=''):
    sidebar = '<a class="nav-title" href="index.html">The field guide</a>'
    for part in dict.fromkeys(c['part'] for c in data['chapters']):
        sidebar += f'<div class="group-label">{part}</div>'
        for c in data['chapters']:
            if c['part'] == part:
                sidebar += f'<a class="{"active" if c["slug"] == slug else ""}" href="{c["slug"]}.html"><span>{c["slug"][:2]}</span>{e(c["title"])}</a>'
    nav = ''.join(f'<a href="{file}.html" {"aria-current=page" if key == active else ""}>{label}</a>' for key,file,label in [('guide','index','Field guide'),('intro','introduction','GenAI 101'),('labs','labs','Interactive labs'),('build','build','Build a repo'),('sources','sources','Sources')])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="An independent, source-linked engineering guide to ChatGPT, Codex and the OpenAI API. Explore patterns and export repository starters."><meta name="theme-color" content="#0e2531"><title>{e(title)} · OpenAI from Docs</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="journey.css"><script src="theme.js"></script><script src="app.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="header"><a class="brand" href="index.html"><b> / </b>OpenAI <span>from docs</span></a><nav aria-label="Primary">{nav}<label class="palette-control"><span class="sr-only">Color theme</span><select id="palette" aria-label="Choose a color theme"><option value="ocean">Ocean</option><option value="violet">Violet</option><option value="ember">Ember</option><option value="forest">Forest</option></select></label><button class="theme-toggle" id="theme" aria-label="Toggle dark theme" aria-pressed="false">◐ Dark</button></nav></header><div class="layout"><aside class="sidebar" aria-label="Chapters"><div class="sidebar-inner">{sidebar}<div class="sidebar-footer">PUBLIC DOCUMENTATION EDITION<br>Reviewed {data['reviewed']}<br><a href="study.html">Reference engineering study ↗</a></div></div></aside><main id="main"><div class="crumb">Engineering library &nbsp; / &nbsp; {e(title)}</div>{body}<footer>Independent educational project. Not affiliated with or endorsed by OpenAI or Anthropic. Original explanations and examples; linked documentation remains the authority.<br><a href="study.html">Reference study</a> · <a href="sources.html">Source ledger</a> · <a href="downloads/openai-from-docs.zip" download>Download website repository</a></footer></main></div></body></html>'''

cards=''.join(f'<a class="chapter-card" data-part="{c["part"]}" data-search="{e((c["title"]+" "+c["summary"]+" "+c["part"]).lower())}" href="{c["slug"]}.html"><div class="number">{"STEP" if c["part"] == "GenAI 101" else "CHAPTER"} {c["slug"][:2]} <small>{c["part"]}</small></div><h3>{e(c["title"])}</h3><p>{e(c["summary"])}</p></a>' for c in data['chapters'])
home=f'''<div class="eyebrow">Public docs. Working patterns. Reviewable code.</div><div class="overview"><div><h1>Understand the system.<br>Build with confidence.</h1><p class="lead">An engineering field guide to ChatGPT, Codex and the OpenAI API. Follow the sources, explore the patterns, then take a starter repository into your own project.</p><a class="button primary" href="introduction.html">Start with GenAI 101 →</a> <a class="button" href="build.html">Build a repository</a></div><div class="map"><div class="eyebrow">The architecture at a glance</div><div class="map-row"><span>ChatGPT<br><small>Experience</small></span><span>Codex<br><small>Engineering</small></span></div><div class="map-row"><span>Your application<br><small>Identity · policy · business logic</small></span></div><div class="map-row"><span>OpenAI API<br><small>Responses · tools · agents</small></span></div><div class="map-base">An application design map, not a claim about proprietary internals.</div></div></div><div class="metrics"><div><strong>{len(data['chapters'])}</strong><span>FOCUSED CHAPTERS</span></div><div><strong>03</strong><span>INTERACTIVE LABS</span></div><div><strong>02</strong><span>REPOSITORY STARTERS</span></div></div><div class="section-head"><h2>Explore the field guide</h2><span class="meta">From foundations to shipping</span></div><label class="meta" for="search">Find a chapter</label><input id="search" class="search" type="search" placeholder="Search tools, state, Codex, evaluation…"><div class="filter" aria-label="Filter by part">{''.join(f'<button data-filter="{p}" aria-pressed="{str(p=="All").lower()}">{p}</button>' for p in ['All'] + list(dict.fromkeys(c['part'] for c in data['chapters'])))}</div><div class="chapter-grid">{cards}</div><p id="empty" class="empty" hidden>No chapters match. Try another term or choose All.</p><p id="search-status" class="meta" aria-live="polite"></p>'''
(OUT/'index.html').write_text(shell('Field guide',home),encoding='utf-8')
intro_cards=''.join(f'<li class="quest-node" data-quest-step="{i}"><a class="chapter-card tilt-card" href="{c["slug"]}.html" data-tilt><div class="number"><span>STAGE {i:02} · {100 if i else 0} XP</span><span class="quest-status" aria-live="polite">Ready</span></div><h3>{e(c["title"])}</h3><p>{e(c["summary"])}</p><span class="quest-action">Enter lesson <span aria-hidden="true">↗</span></span></a></li>' for i,c in enumerate(module['chapters'],1))
intro_body=f'<div class="eyebrow">Your learning campaign / 4 stages</div><div class="journey-hero"><div><h1>{e(module["title"])}<br><span>Questline</span></h1><p class="lead">{e(module["description"])}</p><p>Complete a lesson to earn XP and collect a badge. Your progress stays in this browser.</p></div><div class="journey-orb" aria-hidden="true"><div class="orb-core">AI<small>QUEST</small></div><span class="orb-ring ring-one"></span><span class="orb-ring ring-two"></span><span class="orb-dot dot-one"></span><span class="orb-dot dot-two"></span></div></div><section class="journey-hud panel" aria-labelledby="journey-progress-title"><div class="journey-hud-top"><div><span class="eyebrow">Your progress</span><h2 id="journey-progress-title">The curious mind</h2></div><div class="xp-total"><strong id="xp-total">0</strong><span>XP</span></div></div><div class="progress-track" role="progressbar" aria-label="GenAI 101 journey progress" aria-valuemin="0" aria-valuemax="4" aria-valuenow="0"><span id="progress-fill"></span></div><div class="journey-progress-copy"><span id="progress-copy" aria-live="polite">0 of 4 stages complete</span><span id="next-quest">Next: GenAI for everyone</span></div><div id="badge-shelf" class="badge-shelf" aria-label="Earned badges"><span class="badge-placeholder">Badges appear here as you progress</span></div><button id="reset-journey" class="text-button" type="button">Reset journey progress</button></section><div class="section-head quest-heading"><h2>The four-stage journey</h2><span class="meta">Choose a stage to begin</span></div><ol class="quest-path">{intro_cards}</ol><h2>Sources across the field</h2><p>This module draws on public material from Microsoft, Google Cloud, NIST, Anthropic, a university guide and OpenAI product documentation. Each lesson links directly to the sources behind it.</p><a class="button" href="sources.html">Open the source ledger →</a>'
(OUT/'introduction.html').write_text(shell('GenAI 101',intro_body,'intro'),encoding='utf-8')
for index,c in enumerate(data['chapters']):
    sections=''.join(f'<section><h2>{e(s["title"])}</h2><p>{e(s["body"])}</p></section>' for s in c['sections'])
    nav=(f'<a href="{data["chapters"][index-1]["slug"]}.html">← Previous chapter</a>' if index else '<a href="introduction.html">← GenAI 101</a>')+(f'<a href="{data["chapters"][index+1]["slug"]}.html">Next chapter →</a>' if index<len(data['chapters'])-1 else '<a href="build.html">Build a repository →</a>')
    completion=f'<section class="completion-panel panel" data-journey-step="{module["chapters"].index(c)+1}"><div><span class="eyebrow">Quest checkpoint</span><h2>Finished this stage?</h2><p>Mark it complete to earn 100 XP and add its badge to your journey.</p></div><button class="primary" type="button" data-complete-step>Complete stage · +100 XP</button><p class="completion-status" aria-live="polite"></p></section>' if c in module['chapters'] else ''
    body=f'<article class="article"><div class="eyebrow">{c["part"]} / {"Step" if c["part"] == "GenAI 101" else "Chapter"} {c["slug"][:2]}</div><h1>{e(c["title"])}</h1><p class="lead">{e(c["summary"])}</p><span class="badge">Reviewed {data["reviewed"]}</span>{sections}<div class="code-wrap"><button class="copy">Copy example</button><pre><code>{e(c["code"])}</code></pre></div><h2>Apply this</h2><ul>{"".join(f"<li>{e(a)}</li>" for a in c["apply"])}</ul><h2>Further reading and sources</h2>{refs(c["sources"])}{completion}<div class="chapter-nav">{nav}</div></article>'
    (OUT/(c['slug']+'.html')).write_text(shell(c['title'],body,slug=c['slug']),encoding='utf-8')
    md=f'# {c["title"]}\n\n{c["summary"]}\n\nReviewed: {data["reviewed"]}\n\n'+''.join(f'## {s["title"]}\n\n{s["body"]}\n\n' for s in c['sections'])+'```text\n'+c['code']+'\n```\n\n## Apply this\n\n'+''.join(f'- {a}\n' for a in c['apply'])+'\n## Sources\n\n'+''.join(f'- [{sources[i]["title"]}]({sources[i]["url"]})\n' for i in c['sources'])
    (ROOT/'book'/(c['slug']+'.md')).write_text(md,encoding='utf-8')

labs='''<div class="eyebrow">Learn by changing the inputs</div><h1>Small experiments.<br>Useful mental models.</h1><p class="lead">Three local simulations. No API calls, account access or usage charges.</p><section class="panel"><span class="badge">LAB 01 / TOOL CALLING</span><h2>Step through the action boundary</h2><p>A model requests an operation. Your application decides whether it may run.</p><div class="steps" id="steps"></div><div class="controls"><button id="next-step" class="primary">Next step</button><button id="reset-step">Reset</button><label><input id="deny-tool" type="checkbox" style="width:auto"> Deny authorization</label></div><p id="step-status" class="status" aria-live="polite"></p><a href="05-tool-loop.html">Read the tool-loop chapter →</a></section><section class="panel"><span class="badge">LAB 02 / CONTEXT BUDGET</span><h2>Plan the context you can afford</h2><p>Illustrative arithmetic, not a model limit or price quote. Replace these values with your selected model’s documented limits.</p><div class="form-grid"><div><label for="window">Context window (tokens)</label><input id="window" type="number" min="1" max="10000000" value="32000"></div><div><label for="reserve">Reserved output (tokens)</label><input id="reserve" type="number" min="0" max="10000000" value="4000"></div><div><label for="instructions">Instructions + tools (tokens)</label><input id="instructions" type="number" min="0" max="10000000" value="3000"></div><div><label for="history">Conversation history (tokens)</label><input id="history" type="number" min="0" max="10000000" value="12000"></div></div><p id="budget" class="callout" aria-live="polite"></p></section><section class="panel"><span class="badge">LAB 03 / RELEASE READINESS</span><h2>What evidence is still missing?</h2><p>A planning checklist stored only for this page session. Checking every box does not certify an application.</p><div id="release-checks"></div><p id="release-status" class="status" aria-live="polite"></p><a href="10-release.html">Read the release chapter →</a></section>'''
(OUT/'labs.html').write_text(shell('Interactive labs',labs,'labs'),encoding='utf-8')
builder='''<div class="eyebrow">From a documented contract to a project</div><h1>Take the next step<br>in your own repository.</h1><p class="lead">Export a reviewed starter, your project brief and a source-linked Codex prompt. The export uses templates locally; it does not call a model or generate a finished custom application.</p><div class="panel"><form id="repo-form"><div class="form-grid"><div><label for="project">Repository name</label><input id="project" value="my-openai-app" pattern="[a-z][a-z0-9-]{1,49}" maxlength="50" required><span class="meta">2–50 lowercase letters, digits or hyphens.</span></div><div><label for="starter">Starting point</label><select id="starter"><option value="responses">Responses web app · Node.js</option><option value="codex">Codex project · static web app</option></select></div><div class="full"><label for="brief">What should your application do?</label><textarea id="brief" required maxlength="6000" placeholder="Describe the users, their main task, required data and the acceptance criteria."></textarea></div></div><div class="callout"><strong>Included in every export</strong><p>Runnable source, tests, AGENTS.md, a project brief, official source links, an environment example and release instructions.</p></div><div class="controls"><button class="primary" type="submit">Download repository ZIP ↓</button><button type="button" id="copy-prompt">Copy Codex build prompt</button></div><p id="export-status" class="status" aria-live="polite"></p></form></div><div class="form-grid"><section class="panel"><h3>Repository contents</h3><pre id="file-tree" class="file-tree"></pre></section><section class="panel"><h3>Before a public release</h3><p>The Responses starter runs locally and requires your server-side API key and an available model. Complete authentication, distributed quotas, deployment configuration and live integration testing before exposing it publicly.</p><p>The static Codex starter runs without an API key. Codex can extend it using your brief.</p><a href="10-release.html">Review release gates →</a></section></div>'''
(OUT/'build.html').write_text(shell('Build a repository',builder,'build'),encoding='utf-8')
sourcebody=f'<div class="eyebrow">Evidence ledger / {data["reviewed"]}</div><h1>Follow the source.</h1><p class="lead">Public documentation supports the product contracts. Implementation advice and lab simulations are our own engineering recommendations.</p><div class="callout"><strong>What this guide does not claim</strong><p>It does not reconstruct private ChatGPT or Codex source, guarantee model availability, or certify generated applications. Sources were reviewed on the date above; future changes require a new review.</p></div>{refs(list(sources))}<h2>Reference project</h2><p>We studied the structure and implementation of <a href="https://github.com/alejandrobalderas/claude-code-from-source">Claude Code from Source</a> and its <a href="https://claude-code-from-source.com/">published website</a>. Its source-map research is a different evidence base from this project.</p><a class="button" href="study.html">Read the engineering study →</a>'
(OUT/'sources.html').write_text(shell('Source ledger',sourcebody,'sources'),encoding='utf-8')
study=(ROOT/'research'/'study.html').read_text(encoding='utf-8')
(OUT/'study.html').write_text(shell('Reference engineering study','<article class="article">'+study+'</article>','sources'),encoding='utf-8')
(OUT/'404.html').write_text(shell('Page not found','<h1>This page is not here.</h1><p>Choose a chapter from the field guide.</p><a class="button primary" href="index.html">Back to the guide</a>'),encoding='utf-8')
(OUT/'sources.json').write_text(json.dumps(data['sources'],indent=2),encoding='utf-8')
print(f'Built {len(data["chapters"])} chapters and 7 supporting pages.')
